# Generated by Django 4.1 on 2023-08-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReastApi', '0002_blockip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockIp',
        ),
        migrations.DeleteModel(
            name='CsrfTokenNew',
        ),
    ]
